inactivity/urls.py
"""Routes for Inactivity."""

from django.urls import path

from . import views

app_name = "inactivity"

urlpatterns = [
    path("", views.index, name="index"),
    path("my_requests", views.my_requests, name="my_requests"),
    path("manage_requests", views.manage_requests, name="manage_requests"),
    path(
        "open_requests_data", views.my_open_requests_data, name="my_open_requests_data"
    ),
    path(
        "competed_requests_data",
        views.my_completed_requests_data,
        name="my_completed_requests_data",
    ),
    path(
        "loa_requests/pending",
        views.list_pending_loa_requests,
        name="list_pending_loa_requests",
    ),
    path(
        "loa_requests/approved",
        views.list_processed_loa_requests,
        name="list_processed_loa_requests",
    ),
    path("loa_requests/create", views.create_loa_request, name="create_loa_request"),
    path(
        "loa_requests/<int:loa_request_pk>/cancel",
        views.cancel_loa_request,
        name="cancel_loa_request",
    ),
    path(
        "loa_requests/<int:loa_request_pk>/approve",
        views.approve_loa_request,
        name="approve_loa_request",
    ),
    path(
        "loa_requests/<int:loa_request_pk>/reject",
        views.deny_loa_request,
        name="deny_loa_request",
    ),
    path("inactive_users", views.inactive_users, name="inactive_users"),
    path("inactive_users_data", views.inactive_users_data, name="inactive_users_data"),
]

inactivity/templates/inactivity/partials/menu.html
{% load static %}
{% load i18n %}
{% load navactive %}

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">{% trans "Toggle navigation" %}</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'inactivity:index' %}">Leave of Absence</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="{% navactive request 'inactivity:my_requests' %}">
                    <a href="{% url 'inactivity:my_requests' %}">
                        My requests
                    </a>
                </li>

                {% if perms.inactivity.manage_leave %}
                    <li class="{% navactive request 'inactivity:manage_requests' %}">
                        <a href="{% url 'inactivity:manage_requests' %}">
                            Manage requests&nbsp;
                            {% if unapproved_count > 0 %}
                                <span class="badge badge-nav">{{ unapproved_count }}</span>
                            {% endif %}
                        </a>
                    </li>

                    <li class="{% navactive request 'inactivity:inactive_users' %}">
                        <a href="{% url 'inactivity:inactive_users' %}">
                            Inactive users
                        </a>
                    </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>