inactivity/urls.py
"""Routes for Inactivity."""

from django.urls import path

from . import views

app_name = "inactivity"

urlpatterns = [
    path("", views.index, name="index"),
    path("my_requests", views.my_requests, name="my_requests"),
    path("manage_requests", views.manage_requests, name="manage_requests"),
    path(
        "open_requests_data", views.my_open_requests_data, name="my_open_requests_data"
    ),
    path(
        "competed_requests_data",
        views.my_completed_requests_data,
        name="my_completed_requests_data",
    ),
    path(
        "loa_requests/pending",
        views.list_pending_loa_requests,
        name="list_pending_loa_requests",
    ),
    path(
        "loa_requests/approved",
        views.list_processed_loa_requests,
        name="list_processed_loa_requests",
    ),
    path("loa_requests/create", views.create_loa_request, name="create_loa_request"),
    path(
        "loa_requests/<int:loa_request_pk>/cancel",
        views.cancel_loa_request,
        name="cancel_loa_request",
    ),
    path(
        "loa_requests/<int:loa_request_pk>/approve",
        views.approve_loa_request,
        name="approve_loa_request",
    ),
    path(
        "loa_requests/<int:loa_request_pk>/reject",
        views.deny_loa_request,
        name="deny_loa_request",
    ),
    path("inactive_users", views.inactive_users, name="inactive_users"),
    path("inactive_users_data", views.inactive_users_data, name="inactive_users_data"),
]

inactivity/models.py
"""Models for Inactivity."""

import humanize
from multiselectfield import MultiSelectField
from multiselectfield.utils import get_max_length

from django.contrib.auth.models import Group, User
from django.db import models
from django.utils.html import format_html
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _

from allianceauth.authentication.models import State

from .app_settings import INACTIVITY_TASKS_DEFAULT_PRIORITY
from .helpers import user_for_display
from .managers import InactivityPingConfigManager, LeaveOfAbsenceManager, WebhookManager


class General(models.Model):
    """Meta model for app permissions"""

    class Meta:
        managed = False
        default_permissions = ()
        permissions = (
            ("basic_access", "Can access this app"),
            ("manage_leave", "Can manage leave of absence requests"),
        )


class InactivityPingConfig(models.Model):
    """A ping configuration."""

    name = models.CharField(
        max_length=48,
        unique=True,
        help_text=_("Internal name for the inactivity policy. Must be unique."),
    )
    days = models.PositiveIntegerField(
        help_text=_("The number of days the user must be inactive.")
    )
    text = models.TextField(
        help_text=_("The text of the message or notification sent to the end user.")
    )

    groups = models.ManyToManyField(
        Group,
        blank=True,
        help_text=_(
            "Groups subject to the inactivity policy. If empty, applies to all groups."
        ),
        related_name="+",
    )

    states = models.ManyToManyField(
        State,
        blank=True,
        help_text=_(
            "States subject to the inactivity policy. If empty, applies to all states."
        ),
        related_name="+",
    )

    objects = InactivityPingConfigManager()

    class Meta:
        default_permissions = ()
        verbose_name = _("inactivity policy")
        verbose_name_plural = _("inactivity policies")

    def __str__(self):
        return _("inactivity policy: %(name)s") % {"name": self.name}

    def is_applicable_to(self, user: User) -> bool:
        """Return True if use is applicable to this config, else False."""
        is_applicable = True
        if self.groups.count() > 0:
            is_applicable &= self.groups.filter(user=user).count() > 0
        if self.states.count() > 0:
            is_applicable &= self.states.filter(userprofile=user.profile).count() > 0
        return is_applicable


class InactivityPing(models.Model):
    """An inactive user who has been notified."""

    config = models.ForeignKey(InactivityPingConfig, on_delete=models.CASCADE)
    last_login_at = models.DateTimeField(null=True, default=None)
    timestamp = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="+")

    class Meta:
        default_permissions = ()

    def __str__(self):
        try:
            user_name = self.user.profile.main_character.character_name
        except AttributeError:
            user_name = self.user.username

        return _("ping [policy='%(config_name)s' user='%(user_name)s']") % {
            "config_name": self.config.name,
            "user_name": user_name,
        }


class LeaveOfAbsence(models.Model):
    """A leave of absence request."""

    class Status(models.TextChoices):
        """A leave of absence status."""

        PENDING = "pending"
        APPROVED = "approved"
        DENIED = "denied"

    approver = models.ForeignKey(
        User, on_delete=models.SET_NULL, blank=True, null=True, related_name="+"
    )
    created_at = models.DateTimeField(null=True, default=None)
    reason = models.TextField(
        blank=True,
        null=True,
        default=None,
        help_text=_("Reason for rejecting a request"),
    )
    end = models.DateField(
        blank=True,
        null=True,
        help_text=_(
            "The end of the leave of absence. Leave blank for an indefinite leave."
        ),
    )
    notes = models.TextField(
        blank=True,
        verbose_name="description",
        help_text=_("Description what this leave of absence request is about."),
    )
    start = models.DateField(help_text=_("The start of the leave of absence."))
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="leave_of_absence_requests",
        help_text="The requestor",
    )

    objects = LeaveOfAbsenceManager()

    class Meta:
        default_permissions = ()

    def __str__(self):
        requestor = user_for_display(self.user)
        return _(
            "%(requestor)s's leave of absence request "
            "from %(start)s to %(end)s %(details)s"
        ) % {
            "end": self.end_text,
            "start": self.start,
            "requestor": requestor.name_with_ticker,
            "details": f'"{self.notes[:25]}"' if self.notes else "",
        }

    def save(self, *args, **kwargs) -> None:
        is_new = self._state.adding is True
        if is_new and not self.created_at:
            self.created_at = now()
        return super().save(*args, **kwargs)

    @property
    def approver_name(self) -> str:
        """Name of the approver."""
        if not self.approver:
            return ""
        approver = user_for_display(self.approver)
        return approver.name_with_ticker

    @property
    def end_text(self) -> str:
        """Return text for end property."""
        return str(self.end) if self.end else _("open end")

    @property
    def requestor_name(self) -> str:
        """Name of the requestor."""
        requestor = user_for_display(self.user)
        return requestor.name_with_ticker

    def to_output_dict(self) -> dict:
        """Convert object to an output dictionary."""
        requestor_display = user_for_display(self.user)
        requestor_corporation_name = (
            requestor_display.character.corporation_name
            if requestor_display.character
            else ""
        )
        approver_display = user_for_display(self.approver) if self.approver else None
        duration = (
            humanize.naturaldelta(self.end - self.start) if self.end else _("open end")
        )
        created_at_display = (
            humanize.naturaltime(self.created_at) if self.created_at else "?"
        )
        try:
            status = self.status  # type: ignore
        except AttributeError:
            status_html = ""
        else:
            if status == self.Status.DENIED:
                status_html = format_html(
                    '<span class="text-danger text-underline-dotted" title="{}">{}</span>',
                    f"Reason: {self.reason}",
                    status,
                )
            else:
                status_html = format_html(
                    '<span class="text-success">{}</span>', status
                )

        result = {
            "approver": approver_display.name if approver_display else "",
            "approver_html": approver_display.html if approver_display else "",
            "created_at": {
                "display": created_at_display,
                "sort": self.created_at.isoformat() if self.created_at else "",
            },
            "duration": duration,
            "end": self.end_text,
            "notes": self.notes if self.notes else "-",
            "requestor": requestor_display.name,
            "requestor_html": requestor_display.html,
            "requestor_corporation": requestor_corporation_name,
            "pk": self.pk,
            "start": self.start,
            "status_html": status_html,
        }
        return result


class Webhook(models.Model):
    "A webhook configuration to send message to."

    class NotificationType(models.IntegerChoices):
        """A notification type."""

        INACTIVE_USER = 1, "Inactive User"
        LOA_NEW = 10, "Leave of Absence - Created"
        LOA_APPROVED = 11, "Leave of Absence - Approved"

    class WebhookType(models.IntegerChoices):
        """A type of a webhook."""

        DISCORD = 1, _("Discord Webhook")

    name = models.CharField(
        max_length=64, unique=True, help_text=_("short name to identify this webhook")
    )

    notification_types = MultiSelectField(
        choices=NotificationType.choices,
        max_length=get_max_length(NotificationType.choices, None),
        help_text=_(
            "only notifications of the selected types are sent to this webhook"
        ),
    )

    ping_configs = models.ManyToManyField(
        InactivityPingConfig,
        blank=True,
        help_text=_(
            "The inactivity policies to alert for. "
            "If left blank, all policies are alerted for."
        ),
    )

    url = models.CharField(
        max_length=255,
        unique=True,
        help_text=_(
            "URL of this webhook, e.g. "
            "https://discordapp.com/api/webhooks/123456/abcdef"
        ),
    )
    webhook_type = models.IntegerField(
        choices=WebhookType.choices,
        default=WebhookType.DISCORD,
        help_text=_("type of this webhook"),
    )
    is_active = models.BooleanField(
        default=True,
        help_text=_("whether notifications are currently sent to this webhook"),
    )

    objects = WebhookManager()

    def __str__(self):
        return self.name

    def send_message(self, content: str):
        """Send message to webhook asynchronously."""
        from .tasks import send_message_to_webhook

        if self.webhook_type == self.WebhookType.DISCORD:
            send_message_to_webhook.apply_async(
                kwargs={"webhook_pk": self.pk, "content": content},
                priority=INACTIVITY_TASKS_DEFAULT_PRIORITY,
            )

inactivity/templates/inactivity/base.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}

{% block page_title %}{{ page_title }} - {% translate "Leave of Absence" %}{% endblock %}

{% block content %}
    <br />
    {% include 'inactivity/partials/menu.html' %}
    <h2>{{ page_title }}</h2>
    {% block details %}{% endblock %}
{% endblock %}

inactivity/templates/inactivity/create_loa.html
{% extends 'inactivity/base.html' %}
{% load i18n %}
{% load humanize %}
{% load static %}
{% load bootstrap %}

{% block details %}
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">{% translate "Create Request" %}</h3>
        </div>
        <div class="panel-body" style="min-height: 100px;">
            <form role="form" method="POST" action="{% url 'inactivity:create_loa_request' %}">
                {% csrf_token %}
                {{ form|bootstrap }}
                <div class="form-group">
                    <a class="btn btn-default" href="{% url 'inactivity:my_requests' %}">{% translate "Cancel" %}</a>
                    <div class="pull-right">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block extra_javascript %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" integrity="sha512-uto9mlQzrs59VwILcLiRYeLKPPbS/bT71da/OEBYEwcdNUk8jYIy+D176RYoop1Da+f9mvkYrmj5MCLZWEtQuA==" crossorigin="anonymous"></script>

    <script>
        "use strict";
        $(document).ready(function () {
            let params = {
                dateFormat: "yy-mm-dd"
            };
            $( "#id_start" ).datepicker(params);
            $( "#id_end" ).datepicker(params);
        } );
    </script>
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css"  type="text/css">
{% endblock %}

{% block extra_script %}
{% endblock %}

inactivity/templates/inactivity/inactive_users.html
{% extends 'inactivity/base.html' %}
{% load i18n %}
{% load humanize %}
{% load static %}

{% block details %}

    {% if not has_policies %}
        <div class="alert alert-warning" role="alert">
            If you want to use this page, you need to define an inactivity policy first.
        </div>
    {% endif %}

    <!-- Nav tabs -->
    <ul id="myTabs" class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active">
            <a href="#tab-inactive-users" aria-controls="tab-inactive-users" role="tab" data-toggle="tab">
                {% translate "Currently inactive" %}
            </a>
        </li>
    </ul>

    <div class="panel panel-default panel-tabs">
        <div class="panel-body">
            <div class="tab-content">

                <div role="tabpanel" class="tab-pane active" id="tab-inactive-users">
                    <div class="table-responsive">
                        <table id="table-inactive-users" style="width: 100%;" class="table table-striped">
                            <thead>
                                <tr>
                                    <th>{% translate "Notified" %}</th>
                                    <th>{% translate "User" %}</th>
                                    <th>{% translate "Last login" %}</th>
                                    <th>{% translate "Policy" %}</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>

            </div>
        </div>
    </div>


{% endblock %}

{% block extra_javascript %}

    {% include 'bundles/datatables-js.html' %}
    <script type="application/javascript" src="{% static 'memberaudit/vendor/datatables/plugins/filterDropDown.min.js' %}"></script>

    <script>
        "use strict";
        $(document).ready(function () {

            /* dataTable def */
            let lengthMenu =  [
                [10, 25, 50, 100, -1],
                [10, 25, 50, 100, "All"],
            ];

            $("#table-inactive-users").DataTable({
                ajax: {
                    url: '{% url "inactivity:inactive_users_data" %}',
                    dataSrc: "data",
                    cache: false,
                },

                columns: [
                    {
                        data: 'notified_at',
                        render: {
                            _: 'display',
                            sort: 'sort'
                        }
                    },
                    {
                        data: "user_html",
                        render: {
                            _: 'display',
                            sort: 'sort'
                        }
                    },
                    {
                        data: 'last_login_at',
                        render: {
                            _: 'display',
                            sort: 'sort'
                        }
                    },
                    { data: "policy" },
                    /* hidden */
                    { data: "corporation_name" },
                ],

                lengthMenu: lengthMenu,

                order: [
                    [0, "desc"],
                ],
                columnDefs: [
                    { visible: false, targets: [4] }
                ],
                filterDropDown: {
                    columns: [
                        {
                            idx: 3,
                            maxWidth: "12em"
                        },
                        {
                            idx: 4,
                            title: "{% translate 'Corporation' %}",
                            maxWidth: "12em"
                        }
                    ],
                    bootstrap: true
                },

            });

        });
    </script>

{% endblock %}

{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}
    <link rel="stylesheet" href="{% static 'inactivity/css/aa-bootstrap-fix.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'inactivity/css/inactivity.css' %}" type="text/css">
{% endblock %}

{% block extra_script %}
{% endblock %}

inactivity/templates/inactivity/manage_requests.html
{% extends 'inactivity/base.html' %}
{% load i18n %}
{% load humanize %}
{% load static %}

{% block details %}

    <!-- Nav tabs -->
    <ul id="myTabs" class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active">
            <a href="#tab-pending-requests" aria-controls="tab-pending-requests" role="tab" data-toggle="tab">
                {% translate "Pending" %}
                {% if unapproved_count > 0 %}
                    <span class="badge badge-nav">{{ unapproved_count }}</span>
                {% endif %}
            </a>
        </li>
        <li role="presentation" >
            <a href="#tab-closed-requests" aria-controls="tab-closed-requests" role="tab" data-toggle="tab">
                {% translate "Closed" %}
            </a>
        </li>
    </ul>

    <div class="panel panel-default panel-tabs">
        <div class="panel-body">
            <div class="tab-content">

                <div role="tabpanel" class="tab-pane active" id="tab-pending-requests">
                    <div class="table-responsive">
                        <table id="table-pending-requests" style="width: 100%;" class="table table-striped">
                            <thead>
                                <tr>
                                    <th>{% translate "Submitted" %}</th>
                                    <th>{% translate "Requestor" %}</th>
                                    <th>{% translate "Start" %}</th>
                                    <th>{% translate "End" %}</th>
                                    <th>{% translate "Duration" %}</th>
                                    <th>{% translate "Description" %}</th>
                                    <th></th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>

                <div role="tabpanel" class="tab-pane" id="tab-closed-requests">
                    <div class="table-responsive">
                        <table id="table-closed-requests" style="width: 100%;" class="table table-striped">
                            <thead>
                                <tr>
                                    <th>{% translate "Submitted" %}</th>
                                    <th>{% translate "Requestor" %}</th>
                                    <th>{% translate "Start" %}</th>
                                    <th>{% translate "End" %}</th>
                                    <th>{% translate "Duration" %}</th>
                                    <th>{% translate "Description" %}</th>
                                    <th>{% translate "Result" %}</th>
                                    <th>{% translate "Processed by" %}</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>

            </div>
        </div>
    </div>
    {% include 'inactivity/modals/modal_dialog.html' with name="ViewRequest" %}

{% endblock %}

{% block extra_javascript %}

    {% include 'bundles/datatables-js.html' %}
    <script type="application/javascript" src="{% static 'memberaudit/vendor/datatables/plugins/filterDropDown.min.js' %}"></script>

    <script>
        "use strict";
        $(document).ready(function () {
            let lengthMenu = [
                [10, 25, 50, 100, -1],
                [10, 25, 50, 100, "All"],
            ];

            $("#table-pending-requests").DataTable({
                ajax: {
                    url: '{% url "inactivity:list_pending_loa_requests" %}',
                    dataSrc: "data",
                    cache: false,
                },
                columns: [
                    {
                        data: 'created_at',
                        render: {
                            _: 'display',
                            sort: 'sort'
                        }
                    },
                    { data: "requestor_html" },
                    { data: "start" },
                    { data: "end" },
                    { data: "duration" },
                    { data: "notes" },
                    { data: "actions" },
                    /* visible */
                    { data: "requestor_corporation" },
                ],
                lengthMenu: lengthMenu,
                columnDefs: [
                    {
                        sortable: false, targets: [6],
                        visible: false, targets: [7]
                    }
                ],
                order: [
                    [0, "asc"],
                ],
                filterDropDown: {
                    columns: [
                        {
                            idx: 7,
                            title: "{% translate 'Corporation' %}",
                            maxWidth: "12em"
                        }
                    ],
                    bootstrap: true
                },
            });


            $("#table-closed-requests").DataTable({
                ajax: {
                    url: '{% url "inactivity:list_processed_loa_requests" %}',
                    dataSrc: "data",
                    cache: false,
                },
                columns: [
                    {
                        data: 'created_at',
                        render: {
                            _: 'display',
                            sort: 'sort'
                        }
                    },
                    { data: "requestor_html" },
                    { data: "start" },
                    { data: "end" },
                    { data: "duration" },
                    { data: "notes" },
                    { data: "status_html" },
                    { data: "approver_html" },
                    /* visible */
                    { data: "requestor_corporation" },

                ],
                lengthMenu: lengthMenu,
                order: [
                    [0, "desc"],
                ],
                columnDefs: [
                    {
                        visible: false, targets: [8]
                    }
                ],
                filterDropDown: {
                    columns: [
                        {
                            idx: 8,
                            title: "{% translate 'Corporation' %}",
                            maxWidth: "12em"
                        }
                    ],
                    bootstrap: true
                },

            });
        });
    </script>

{% endblock %}

{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}
    <link rel="stylesheet" href="{% static 'inactivity/css/aa-bootstrap-fix.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'inactivity/css/inactivity.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'inactivity/css/manage_requests.css' %}" type="text/css">
{% endblock %}

{% block extra_script %}
{% endblock %}

inactivity/templates/inactivity/my_requests.html
{% extends 'inactivity/base.html' %}
{% load i18n %}
{% load humanize %}
{% load static %}

{% block details %}

    <span class="pull-right">
        <a class="btn btn-success btn-tabs" href="{% url 'inactivity:create_loa_request' %}">
            {% translate "Create Request" %}
        </a>
    </span>

    <!-- Nav tabs -->
    <ul id="myTabs" class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active">
            <a href="#tab-pending-requests" aria-controls="tab-pending-requests" role="tab" data-toggle="tab">
                {% translate "Pending" %}
            </a>
        </li>
        <li role="presentation" >
            <a href="#tab-closed-requests" aria-controls="tab-closed-requests" role="tab" data-toggle="tab">
                {% translate "Closed" %}
            </a>
        </li>
    </ul>

    <div class="panel panel-default panel-tabs">
        <div class="panel-body">
            <div class="tab-content">

                <div role="tabpanel" class="tab-pane active" id="tab-pending-requests">
                    <div class="table-responsive">
                        <table id="table-pending-requests" style="width: 100%;" class="table table-striped">
                            <thead>
                                <tr>
                                    <th>{% translate "Submitted" %}</th>
                                    <th>{% translate "Start" %}</th>
                                    <th>{% translate "End" %}</th>
                                    <th>{% translate "Duration" %}</th>
                                    <th>{% translate "Description" %}</th>
                                    <th></th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>

                <div role="tabpanel" class="tab-pane" id="tab-closed-requests">
                    <div class="table-responsive">
                        <table id="table-closed-requests" style="width: 100%;" class="table table-striped">
                            <thead>
                                <tr>
                                    <th>{% translate "Submitted" %}</th>
                                    <th>{% translate "Start" %}</th>
                                    <th>{% translate "End" %}</th>
                                    <th>{% translate "Duration" %}</th>
                                    <th>{% translate "Description" %}</th>
                                    <th>{% translate "Result" %}</th>
                                    <th>{% translate "Processed By" %}</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>

            </div>
        </div>
    </div>


{% endblock %}

{% block extra_javascript %}

    {% include 'bundles/datatables-js.html' %}

    <script>
        "use strict";
        $(document).ready(function () {

            /* dataTable def */
            let lengthMenu =  [
                [10, 25, 50, 100, -1],
                [10, 25, 50, 100, "All"],
            ];

            $("#table-pending-requests").DataTable({
                ajax: {
                    url: '{% url "inactivity:my_open_requests_data" %}',
                    dataSrc: "data",
                    cache: false,
                },

                columns: [
                    {
                        data: 'created_at',
                        render: {
                            _: 'display',
                            sort: 'sort'
                        }
                    },
                    { data: "start" },
                    { data: "end" },
                    { data: "duration" },
                    { data: "notes" },
                    { data: "actions" },
                ],

                lengthMenu: lengthMenu,

                columnDefs: [
                    { sortable: false, targets: [5] }
                ],

                order: [
                    [0, "desc"],
                ],
            });

            $("#table-closed-requests").DataTable({
                ajax: {
                    url: '{% url "inactivity:my_completed_requests_data" %}',
                    dataSrc: "data",
                    cache: false,
                },

                columns: [
                    {
                        data: 'created_at',
                        render: {
                            _: 'display',
                            sort: 'sort'
                        }
                    },
                    { data: "start" },
                    { data: "end" },
                    { data: "duration" },
                    { data: "notes" },
                    { data: "status_html" },
                    { data: "approver_html" },
                ],

                lengthMenu: lengthMenu,

                order: [
                    [0, "desc"],
                ],
            });

        });
    </script>

{% endblock %}

{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}
    <link rel="stylesheet" href="{% static 'inactivity/css/aa-bootstrap-fix.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'inactivity/css/inactivity.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'inactivity/css/my_requests.css' %}" type="text/css">
{% endblock %}

{% block extra_script %}
{% endblock %}

inactivity/templates/inactivity/reject_request.html
{% extends 'inactivity/base.html' %}
{% load i18n %}
{% load humanize %}
{% load static %}
{% load bootstrap %}

{% block details %}
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">{% translate "Deny Request" %}</h3>
        </div>

        <div class="panel-body" style="min-height: 100px;">
            <form role="form" method="POST" action="{% url 'inactivity:deny_loa_request' loa_request.pk %}">
                {% csrf_token %}
                {{ form|bootstrap }}
                <div class="form-group">
                    <a class="btn btn-default" href="{% url 'inactivity:manage_requests' %}">{% translate "Cancel" %}</a>
                    <div class="pull-right">
                        <button type="submit" class="btn btn-danger">Deny</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}